version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000" # Expose port 5000 for the Flask app
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
    volumes:
      - .:/app # Mount the current directory to /app inside the container
    stdin_open: true
    tty: true
